
FUNCTION BUSCANMES
PARAMETERS PmES
	DO case
	CASE pMes=1
		RETURN 'ENERO'
	CASE pMes=2
		RETURN 'FEBRERO'
	CASE pMes=3
		RETURN 'MARZO'
	CASE pMes=4
		RETURN 'ABRIL'
	CASE pMes=5
		RETURN 'MAYO'
	CASE pMes=6
		RETURN 'JUNIO'
	CASE pMes=7
		RETURN 'JULIO'
	CASE pMes=8
		RETURN 'AGOSTO'
	CASE pMes=9
		RETURN 'SETIEMBRE'
	CASE pMes=10
		RETURN 'OCTUBRE'
	CASE pMes=11
		RETURN 'NOVIEMBRE'
	CASE pMes=12
		RETURN 'DICIEMBRE'
	ENDCASE

ENDFUNC 